---
- name: configure prometheus
  copy:
    src: prometheus.yml
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
  notify:
    - restart prometheus