---
- name: Import Grafana GPG signing key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: Add Grafana repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: latest
  notify:
    - enable service grafana
    - restart grafana